{
 "title": "Company Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "search_countries", "query": { "query": "search_inbound_total" } }
  ]
 },
 "panels": [
  {
   "title": "Search Requests ($search_countries)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "API Inbound ($search_countries)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(search_inbound_total{country=~\"$search_countries\"})"
    }
   ]
  },
  {
   "title": "API errors ($search_countries)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(search_scrapers_error_total{country=~\"$search_countries\"})"
    }
   ]
  },
  {
   "title": "API inbound  per country ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "search_inbound_total{country=~\"$search_countries\"}",
     "legendFormat": "API Inbound ({{country}})"
    }
   ]
  },
  {
   "title": "API Found vs Not Found ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "search_outbound_found_in_repo_total{country=~\"$search_countries\"}",
     "legendFormat": "Results found in repo ({{country}})"
    },
    {
     "expr": "search_found_in_scrapers_total{country=~\"$search_countries\"}",
     "legendFormat": "Results found in Scrapers ({{country}})"
    },
    {
     "expr": "search_outbound_not_found_total{country=~\"$search_countries\"}",
     "legendFormat": "Results not found ({{country}})"
    }
   ]
  },
  {
   "title": "API errors ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(search_scrapers_error_total{country=~\"$search_countries\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "search_scrapers_error_total{country=~\"$search_countries\"}",
     "legendFormat": "Error ({{country}}, statusCode: {{statusCode}})"
    }
   ]
  },
  {
   "title": "ScraperService Inbound ($search_countries)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lookup_inbound_total{country=~\"$search_countries\"})"
    }
   ]
  },
  {
   "title": "ScraperService errors ($search_countries)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lookup_error_total{country=~\"$search_countries\"})"
    }
   ]
  },
  {
   "title": "ScraperService inbound  per country ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "lookup_inbound_total{country=~\"$search_countries\"}",
     "legendFormat": "ScraperService Inbound ({{country}})"
    }
   ]
  },
  {
   "title": "ScraperService Found vs Not Found ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "lookup_outbound_found_total{country=~\"$search_countries\", reason != \"\"}",
     "legendFormat": "Results found ({{country}}, scraper {{scraperName}})"
    },
    {
     "expr": "lookup_outbound_not_found_total{country=~\"$search_countries\", reason != \"\"}",
     "legendFormat": "Results not found ({{country}}, {{reason}})"
    }
   ]
  },
  {
   "title": "ScraperService errors ($search_countries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(lookup_error_total{country=~\"$search_countries\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "lookup_error_total{country=~\"$search_countries\", scraperName != \"\"}",
     "legendFormat": "Error ({{country}}, statusCode: {{statusCode}}, scraper {{scraperName}})"
    },
    {
     "expr": "lookup_error_total{country=~\"$search_countries\", scraperName = \"\"}",
     "legendFormat": "Error ({{country}}, statusCode: {{statusCode}})"
    }
   ]
  }
 ]
}