apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-api
  labels:
    app: api
  namespace: company-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: company-api
          # Before running, replace ECR_REGISTRY with your registry.
          image: $ECR_REGISTRY/company-service/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: company-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: company-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30202
