name: test company-service

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: checkout the files
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}

      - name: install dependencies
        run: npm install

      - name: run unit tests
        run: npm run test

      - name: set up local mongo
        run: sudo docker run -d -p 27017:27017 mongo:latest

      - name: run e2e tests
        run: npm run test:e2e

      - name: check code formatting
        run: npm run format:check
